# Generated by Django 3.0.5 on 2022-04-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timetable', models.ImageField(blank=True, null=True, upload_to='Timetable/exam/')),
            ],
        ),
    ]
